name: "[논의] "
description: "논의를 시작할 때 참고할 정보를 입력하세요."
title: "[논의] 제목"
body:
  - type: markdown
    attributes:
      value: "## 논의 배경\n이 논의의 배경이나 맥락을 설명해주세요. 문제점, 아이디어의 출처, 관련된 자료나 정보를 포함하세요."
  - type: textarea
    id: background
    attributes:
      label: 논의 배경
      description: 이 논의를 시작하게 된 이유와 관련된 배경 정보를 입력하세요.
      placeholder: "예: 문제의 원인, 관련된 이슈, 제안된 솔루션 등"
