title: "[논의] "
labels: ["🙋‍♂️ Question"]
body:
  - type: markdown
    attributes:
      value: |
        논의하고 싶은 세부 주제에 대해 작성해주세요.
  - type: textarea
    id: improvements
    attributes:
      label: 세부 주제
      description: "논의하고 싶은 세부 주제에 대해 작성해주세요."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
